### ISSUE TITLE
[Idea] Anchor links

### ISSUE THREAD

**Issue by mdzierzkowski** [nas5w/100-days-of-code-frontend#3]
Hi.

I have an idea to add anchor links in "day-by-day" list like in my fork: https://github.com/mdzierzkowski/100-days-of-code-frontend/blob/anchors/README.md

I can make a PR if you like my idea. 

PS: Thank you for this document, I found it very helpful.
PPS: It's my very first contribuiton to someone's repository on github.

**Comment by nas5w** [comment]
Love the idea! Please do a pull request.

Welcome to contributing and thank you :+1:

**Comment by nas5w** [comment]
Thanks again, [you're now a contributor](https://github.com/nas5w/100-days-of-code-frontend/graphs/contributors)! :clap:

**Comment by mdzierzkowski** [comment]
Thank you. 👍
I'm glad that I could help. 😄
